<<<<<<< HEAD
CREATE TABLE users(
  id INT generated by default as identity PRIMARY KEY,
  display_name varchar NOT NULL,
  username VARCHAR NOT NULL,
  password VARCHAR NOT NULL
);
=======
CREATE TABLE users(
  id INT generated by default as identity PRIMARY KEY,
  display_name varchar NOT NULL,
  username VARCHAR NOT NULL,
  password VARCHAR NOT NULL
);
>>>>>>> d7ea2880fd9b8fad3bea19c28dd338fab60535de
