DROP TABLE IF EXISTS meals;
CREATE TABLE meals(
  id integer GENERATED BY DEFAULT AS IDENTITY,
  food integer ARRAY,
  ingredients integer ARRAY,
  user integer REFERENCES 'users'(id),
  created timestamptz
);