DROP TABLE IF EXISTS symptoms;

CREATE TABLE symptoms(
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type varchar NOT NULL,
  severity_id INTEGER REFERENCES "severity"(id),
  user_id INTEGER REFERENCES users(id),
  created timestamptz DEFAULT NOW()
);