DROP TABLE IF EXIST symptoms ON DELETE CASCADE;
CREATE TBALE symptoms(
  id INT GENERATED BY DEFAULT AS IDENTITY,
  type varchar NOT NULL,
  severity INT REFERENCES severity(id),
  user INT REFERENCES users(id),
  created TIMESTAMPTZ
);