DROP TABLE if exists symptom_set;
CREATE TABLE symptom_set(
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  symptom_name varchar NOT NULL,
  min_time_passed NUMERIC DEFAULT 0.5,
  max_time_passed NUMERIC DEFAULT 48,
  user_id INTEGER REFERENCES users(id),
  created timestamptz DEFAULT NOW()
)